### ISSUE TITLE
Form Submission

### ISSUE THREAD

**Issue by rickychilcott** [Rakefire/stevenheffner.com#2]
I believe I have form submission working correctly. That said, it's not using the ajax process. We should read through `js/contact.js` in the repo to see if we can figure out why.

**Comment by rickychilcott** [comment]
This appears to be working OK now. Likely fixed in the first commit.

https://github.com/Rakefire/stevenheffner.com/commit/f9f8245873659f562f7f2dabee015b38ed68fc59
https://github.com/Rakefire/stevenheffner.com/commit/16f14c47a0fb19e65f6241e86cbc5f76990e965a
https://github.com/Rakefire/stevenheffner.com/commit/9c0684c6da4b92aa881fa9e7cd92420206244910

**Comment by timothywasserman** [comment]
Nice, thanks. It seems to be working for me.
